version: '3.7'

services:
  dashboard:
    container_name: "saleor-dashboard"
    build:
      context: ./saleor-dashboard
      args: 
        API_URI: 'https://example.com/graphql/'
        APP_MOUNT_URI: '/dashboard/'
        STATIC_URL: '/dashboard/'
      dockerfile: Dockerfile
    volumes:
      - dashboard:/app/build
    networks:
      saleor-backend-tier:
        aliases: 
          - dashboard
  storefront:
    container_name: "saleor-storefront"
    build:
      context: ./saleor-storefront
      args: 
        API_URI: 'https://example.com/graphql/'
      dockerfile: Dockerfile
    volumes:
      - storefront:/app/dist
    networks:
      saleor-backend-tier:
        aliases: 
          - storefront
  letsencrypt:
    image: adferrand/letsencrypt-dns
    container_name: "letsencrypt-dns"
    command: >
      /bin/bash -c "openssl dhparam -dsaparam -out /etc/letsencrypt/ssl-dhparams.pem 4096
      && /scripts/run.sh"
    env_file: common.env
    volumes:
      - ./config/letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
      - ./config/letsencrypt/:/etc/letsencrypt
    restart: always
    networks:
      saleor-backend-tier:
        aliases: 
          - letsencrypt
  nginx:
    image: nginx:stable
    container_name: "nginx-ingress"
    env_file: common.env
    restart: always
    command: >
        /bin/bash -c "envsubst < /etc/nginx/conf.d/template > /etc/nginx/conf.d/default.conf 
        && exec nginx -g 'daemon off;'"
    depends_on:
      - letsencrypt
      - dashboard
      - storefront
    volumes: 
      - ./config/letsencrypt:/etc/letsencrypt
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/misc:/etc/nginx/misc
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/logs:/var/log/nginx
      - saleor-media:/app/media:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      saleor-backend-tier:
        aliases: 
          - nginx

volumes:
  dashboard:
  storefront:
  saleor-media:
    external:
      name: saleor_saleor-media

networks:
  saleor-backend-tier:
    external:
      name: saleor_saleor-backend-tier
